"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import Image from "next/image"
import Link from "next/link"
import { useQuery } from "@tanstack/react-query"
import { Badge } from "@/components/ui/badge"
import { ExternalLink, ArrowRight, Coins, Shield, Palette, TrendingUp, Crosshair, Trophy, CalendarClock, Newspaper } from "lucide-react"

const containerVariants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.08, delayChildren: 0.1 } },
}

const cardVariants = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" as const } },
}

const chainColors: Record<string, string> = {
  cardano: "#0033AD",
  midnight: "#6366F1",
  ethereum: "#627EEA",
  bitcoin: "#F7931A",
}

type ProjectLink = { label: string; url: string }

type Project = {
  name: string
  tagline: string
  description: string
  status: string
  statusColor: string
  categories: string[]
  chain: "cardano" | "midnight" | "ethereum" | "bitcoin"
  icon: React.ElementType
  href?: string
  externalHref?: string
  links?: ProjectLink[]
  images?: { src: string; alt: string; contain?: boolean }[]
  stats?: { label: string; value: string }[]
  gradient: string
}

const projects: Project[] = [
  {
    name: "Good Vibes Club",
    tagline: "Kill Em' With Kindness",
    description:
      "6,968 meticulously crafted 3D PFP NFTs on Ethereum by award-winning animation studio Toast. An art-forward IP built around Vibetown with a thriving builder community: Vibe Off, Smash The Wall, SpotiVibe, GVC Badges, and AI tools.",
    status: "Holder",
    statusColor: "bg-purple-500/20 text-purple-400 border-purple-500/30",
    categories: ["NFT", "Ethereum", "Community"],
    chain: "ethereum",
    icon: Palette,
    externalHref: "https://opensea.io/collection/good-vibes-club",
    links: [
      { label: "Website", url: "https://www.goodvibesclub.io" },
      { label: "OpenSea", url: "https://opensea.io/collection/good-vibes-club" },
    ],
    images: [{ src: "/avatar/character.jpg", alt: "Good Vibes Club 3D PFP" }],
    stats: [
      { label: "Supply", value: "6,968" },
      { label: "Volume", value: "13.5K ETH" },
    ],
    gradient: "from-purple-500/15 via-transparent to-transparent",
  },
  {
    name: "Liqwid Finance",
    tagline: "Cardano's Leading Lending Protocol",
    description:
      "$32M+ TVL and growing. Non-custodial lending and borrowing for ADA and Cardano native tokens. Unique Lombard loans let you borrow against staked ADA without losing staking rewards. LQ governance token and NFT collection for boosted rewards.",
    status: "Active",
    statusColor: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
    categories: ["DeFi", "Cardano", "Lending"],
    chain: "cardano",
    icon: Coins,
    externalHref: "https://app.liqwid.finance",
    links: [
      { label: "Website", url: "https://liqwid.finance" },
      { label: "App", url: "https://app.liqwid.finance" },
    ],
    images: [{ src: "/avatar/robot_character.jpg", alt: "Liqwid Finance NFT rewards booster" }],
    stats: [
      { label: "TVL", value: "$32M+" },
      { label: "Protocol", value: "Lending" },
    ],
    gradient: "from-cyan-500/15 via-transparent to-transparent",
  },
  {
    name: "Midnight",
    tagline: "Data Protection Blockchain",
    description:
      "Built by IOG from the Cardano ecosystem. Mainnet launched March 2026 with a fair NIGHT token airdrop to 37M wallets. ZK-powered hybrid ledger mixing public and private data. Early node operators include Worldpay, MoneyGram, and Google Cloud.",
    status: "Active",
    statusColor: "bg-indigo-500/20 text-indigo-400 border-indigo-500/30",
    categories: ["L1", "Privacy", "ZK"],
    chain: "midnight",
    icon: Shield,
    externalHref: "https://midnight.network",
    links: [
      { label: "Network", url: "https://midnight.network" },
      { label: "City", url: "https://midnight.city" },
    ],
    images: [{ src: "/avatar/circle_dots_icon.jpg", alt: "Midnight Network logo", contain: true }],
    stats: [
      { label: "Launch", value: "Mar 2026" },
      { label: "Token", value: "NIGHT" },
    ],
    gradient: "from-indigo-500/15 via-transparent to-transparent",
  },
  {
    name: "Arbiter",
    tagline: "Tokenized Forex Assets on Cardano",
    description:
      "1,718 utility NFTs backed by ATS, a Dubai-based automated forex trading firm. Holders earn passive ADA rewards from treasury profits generated by AUD/CAD forex strategies. No tokens, all value stays in the NFTs. Transparent results tracked on Myfxbook.",
    status: "Holder",
    statusColor: "bg-amber-500/20 text-amber-400 border-amber-500/30",
    categories: ["NFT", "Cardano", "Forex"],
    chain: "cardano",
    icon: TrendingUp,
    externalHref: "https://www.wayup.io/collection/b6e45677ddc7d582efa689c29221efcba40c6230d477591d65dfd02e",
    links: [{ label: "Collection", url: "https://www.wayup.io/collection/b6e45677ddc7d582efa689c29221efcba40c6230d477591d65dfd02e" }],
    images: [{ src: "/avatar/cyber_character.jpg", alt: "Arbiter NFT cyber character" }],
    stats: [
      { label: "Supply", value: "1,718" },
      { label: "Floor", value: "₳99" },
    ],
    gradient: "from-amber-500/15 via-transparent to-transparent",
  },
]

const filterChains = ["all", "cardano", "midnight", "ethereum"] as const

// ── Live stats for the signals suite (what is actually running today) ───────

interface PerfResp {
  stats: { kpis: { closedN: number; openN: number; tp1Rate: number | null } }
}
interface HotResp {
  hot: { symbol: string }[]
  all: { symbol: string }[]
}
interface MacroResp {
  upcoming: { title: string; time: string; importance: string }[]
}

function useSignalsLive() {
  const perf = useQuery<PerfResp>({
    queryKey: ["projects-perf"],
    queryFn: async () => {
      const r = await fetch("/api/signals/history?view=performance&range=all&dedupe=1&limit=1")
      if (!r.ok) throw new Error("perf")
      return r.json()
    },
    refetchInterval: 60_000,
    retry: false,
  })
  const hot = useQuery<HotResp>({
    queryKey: ["signals-hot"],
    queryFn: async () => {
      const r = await fetch("/api/signals/hot")
      if (!r.ok) throw new Error("hot")
      return r.json()
    },
    refetchInterval: 60_000,
    retry: false,
  })
  const macro = useQuery<MacroResp>({
    queryKey: ["projects-macro"],
    queryFn: async () => {
      const r = await fetch("/api/macro")
      if (!r.ok) throw new Error("macro")
      return r.json()
    },
    refetchInterval: 60_000,
    retry: false,
  })
  return { perf: perf.data, hot: hot.data, macro: macro.data }
}

function StatusBadge({ status, className }: { status: string; className: string }) {
  return (
    <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium ${className}`}>
      <span className="size-1.5 rounded-full bg-current" />
      {status}
    </span>
  )
}

function LiveDot({ color }: { color: string }) {
  return (
    <span className="relative flex size-1.5">
      <span className="absolute inline-flex size-full animate-ping rounded-full opacity-75" style={{ backgroundColor: color }} />
      <span className="relative inline-flex size-1.5 rounded-full" style={{ backgroundColor: color }} />
    </span>
  )
}

function Stat({ value, label, color }: { value: string; label: string; color?: string }) {
  return (
    <div className="text-center">
      <div className="font-mono text-lg font-bold" style={{ color: color ?? "rgba(255,255,255,0.9)" }}>{value}</div>
      <div className="mt-0.5 text-xs uppercase tracking-wider text-white/40">{label}</div>
    </div>
  )
}

const GREEN = "#00FF88"
const STRIKE = "#4EFAB0"
const ASCEND = "#F35233"

function FeaturedSignalsCard() {
  const { perf, hot, macro } = useSignalsLive()
  const closedN = perf?.stats.kpis.closedN
  const tp1 = perf?.stats.kpis.tp1Rate
  const hotN = hot?.hot?.length
  const next = macro?.upcoming?.[0]

  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="relative mb-6 overflow-hidden rounded-2xl border p-8 backdrop-blur-xl"
      style={{ borderColor: `${GREEN}33`, background: `linear-gradient(135deg, ${GREEN}10 0%, rgba(10,14,23,0.6) 60%)` }}
    >
      <div className="flex flex-col gap-8 lg:flex-row lg:items-center">
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex size-10 shrink-0 items-center justify-center rounded-xl" style={{ backgroundColor: `${GREEN}1A`, boxShadow: `inset 0 0 0 1px ${GREEN}40` }}>
              <Crosshair className="size-5" style={{ color: GREEN }} />
            </div>
            <h2 className="font-display text-xl font-bold tracking-tight lg:text-2xl">Signals</h2>
            <span className="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium" style={{ borderColor: `${GREEN}4D`, backgroundColor: `${GREEN}26`, color: GREEN }}>
              <LiveDot color={GREEN} /> LIVE
            </span>
          </div>
          <p className="mt-1 text-sm text-white/40">Plain-English trade calls, refreshed every 30 seconds</p>
          <p className="mt-3 max-w-2xl text-[15px] leading-relaxed text-white/60">
            One recommendation per market across 31 crypto, commodity, stock and index tickers: action, conviction, entry, stop and targets, with every reason deep-linked to the chart or statistic behind it. Catalyst headline engines for WTI, Bitcoin, Gold and Cardano, a macro event calendar with verified post-release surprise analysis, and a track record checked against 5-minute candles.
          </p>

          <div className="mt-6 flex flex-wrap gap-6">
            <Stat value="31" label="Markets" />
            <Stat value={hotN == null ? "---" : String(hotN)} label="Hot plays now" color={GREEN} />
            <Stat value={closedN == null ? "---" : String(closedN)} label="Closed signals" />
            <Stat value={tp1 == null ? "---" : `${tp1.toFixed(0)}%`} label="TP1 hit rate" color={tp1 == null ? undefined : tp1 >= 50 ? GREEN : "#FF3B5C"} />
          </div>

          <div className="mt-6 flex flex-wrap gap-3">
            <Link href="/signals" className="inline-flex items-center gap-2 rounded-full px-6 py-2.5 text-sm font-semibold text-[#06080F] transition-opacity hover:opacity-90" style={{ backgroundColor: GREEN }}>
              Open Signals <ArrowRight className="size-4" />
            </Link>
            <Link href="/signals/performance" className="inline-flex items-center gap-2 rounded-full border border-white/[0.1] px-5 py-2.5 text-sm text-white/60 transition-colors hover:border-white/[0.2] hover:text-white/80">
              <Trophy className="size-3.5" /> Performance
            </Link>
          </div>
        </div>

        <div className="hidden w-[300px] shrink-0 space-y-3 lg:block">
          <div className="rounded-xl border border-white/[0.08] bg-black/30 p-4">
            <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-white/40"><Newspaper className="size-3.5" /> Catalyst engines</div>
            <div className="mt-1.5 text-sm text-white/75">WTI · Bitcoin · Gold · Cardano</div>
            <div className="text-[11px] text-white/40">Headlines scored, price reaction per story, two-force verdict</div>
          </div>
          <div className="rounded-xl border border-white/[0.08] bg-black/30 p-4">
            <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-white/40"><CalendarClock className="size-3.5" /> Next macro event</div>
            <div className="mt-1.5 text-sm text-white/75">{next ? next.title : "---"}</div>
            <div className="text-[11px] text-white/40">{next ? new Date(next.time).toLocaleString(undefined, { weekday: "short", hour: "numeric", minute: "2-digit" }) : "loading"}</div>
          </div>
        </div>
      </div>
      <div className="pointer-events-none absolute inset-x-0 bottom-0 h-px" style={{ background: `linear-gradient(90deg, transparent, ${GREEN}66, transparent)` }} />
    </motion.div>
  )
}

function VenueSignalsCard({ name, color, logo, tagline, description, href, venue, markets }: { name: string; color: string; logo: string; tagline: string; description: string; href: string; venue: { label: string; url: string }; markets: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="relative overflow-hidden rounded-2xl border p-6 backdrop-blur-xl"
      style={{ borderColor: `${color}33`, background: `linear-gradient(135deg, ${color}12 0%, rgba(10,14,23,0.6) 60%)` }}
    >
      <div className="flex items-center gap-3">
        <div className="relative size-10 shrink-0 overflow-hidden rounded-xl ring-1" style={{ ["--tw-ring-color" as string]: `${color}4D` } as React.CSSProperties}>
          <Image src={logo} alt={name} fill className="object-cover" />
        </div>
        <h3 className="font-display text-lg font-bold tracking-tight">{name}</h3>
        <span className="ml-auto inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium" style={{ borderColor: `${color}4D`, backgroundColor: `${color}26`, color }}>
          <LiveDot color={color} /> LIVE
        </span>
      </div>
      <p className="mt-1 text-sm text-white/40">{tagline}</p>
      <p className="mt-3 text-sm leading-relaxed text-white/60">{description}</p>
      <div className="mt-4 text-[11px] uppercase tracking-wider text-white/40">Markets: <span className="font-mono text-white/70 normal-case tracking-normal">{markets}</span></div>
      <div className="mt-5 flex flex-wrap gap-3">
        <Link href={href} className="inline-flex items-center gap-2 rounded-full px-5 py-2 text-sm font-semibold text-[#06080F] transition-opacity hover:opacity-90" style={{ backgroundColor: color }}>
          Open {name} <ArrowRight className="size-4" />
        </Link>
        <a href={venue.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/[0.1] px-4 py-2 text-sm text-white/60 transition-colors hover:border-white/[0.2] hover:text-white/80">
          <ExternalLink className="size-3.5" /> {venue.label}
        </a>
      </div>
      <div className="pointer-events-none absolute inset-x-0 bottom-0 h-px" style={{ background: `linear-gradient(90deg, transparent, ${color}66, transparent)` }} />
    </motion.div>
  )
}

const projectAccents: Record<string, string> = {
  "Good Vibes Club": "#A855F7",
  "Liqwid Finance": "#22D3EE",
  Midnight: "#818CF8",
  Arbiter: "#F59E0B",
}

function ProjectCard({ project }: { project: Project }) {
  const chainColor = chainColors[project.chain]
  const accent = projectAccents[project.name] ?? chainColor

  return (
    <motion.div
      layout
      variants={cardVariants}
      initial="hidden"
      animate="show"
      exit={{ opacity: 0, scale: 0.95, transition: { duration: 0.2 } }}
      className="group relative flex flex-col overflow-hidden rounded-2xl border transition-all duration-300 backdrop-blur-md"
      style={{
        borderColor: `color-mix(in srgb, ${accent} 15%, transparent)`,
        background: `linear-gradient(135deg, color-mix(in srgb, ${accent} 6%, rgba(10,14,23,0.6)) 0%, rgba(10,14,23,0.6) 60%)`,
      }}
    >
      <div className="pointer-events-none absolute inset-x-0 top-0 h-px" style={{ background: `linear-gradient(90deg, transparent, ${accent}40, transparent)` }} />
      {project.images && project.images.length > 0 && (
        <div className={`relative h-48 w-full overflow-hidden ${project.images[0].contain ? "bg-[#0A0E17]" : ""}`}>
          <Image src={project.images[0].src} alt={project.images[0].alt} fill className={`transition-transform duration-500 group-hover:scale-105 ${project.images[0].contain ? "object-contain p-8" : "object-cover"}`} sizes="(max-width: 768px) 100vw, 33vw" />
          <div className="absolute inset-0 bg-gradient-to-t from-[#06080F] via-[#06080F]/40 to-transparent" />
        </div>
      )}
      <div className="relative flex flex-1 flex-col p-6">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex size-10 shrink-0 items-center justify-center rounded-xl" style={{ backgroundColor: `color-mix(in srgb, ${accent} 12%, transparent)`, boxShadow: `inset 0 0 0 1px color-mix(in srgb, ${accent} 25%, transparent)` }}>
              <project.icon className="size-5" style={{ color: accent }} />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-display text-lg font-bold tracking-tight">{project.name}</h3>
                <span className="flex items-center gap-1 text-[10px] uppercase tracking-wider text-white/40">
                  <span className="size-2 rounded-full" style={{ backgroundColor: chainColor }} />
                  {project.chain}
                </span>
              </div>
              <p className="text-sm text-white/40">{project.tagline}</p>
            </div>
          </div>
          <StatusBadge status={project.status} className={project.statusColor} />
        </div>
        <p className="mt-4 text-sm leading-relaxed text-white/60">{project.description}</p>
        {project.stats && project.stats.length > 0 && (
          <div className="mt-5 flex gap-6 rounded-xl px-5 py-3.5" style={{ backgroundColor: `color-mix(in srgb, ${accent} 5%, transparent)` }}>
            {project.stats.map((stat) => (
              <div key={stat.label}>
                <div className="text-[10px] uppercase tracking-wider text-white/30">{stat.label}</div>
                <div className="font-mono text-sm font-bold" style={{ color: accent }}>{stat.value}</div>
              </div>
            ))}
          </div>
        )}
        <div className="mt-auto pt-5 flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap gap-1.5">
            {project.categories.map((cat) => (
              <Badge key={cat} variant="secondary" className="border-white/[0.06] bg-white/[0.04] text-[11px] text-white/50">{cat}</Badge>
            ))}
          </div>
          <div className="flex items-center gap-2">
            {project.links ? (
              project.links.map((link) => (
                <a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium text-white/40 transition-colors hover:bg-white/[0.06] hover:text-white/70">
                  <ExternalLink className="size-3.5" /> {link.label}
                </a>
              ))
            ) : project.externalHref ? (
              <a href={project.externalHref} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium text-white/40 transition-colors hover:bg-white/[0.06] hover:text-white/70">
                <ExternalLink className="size-3.5" /> Visit
              </a>
            ) : null}
          </div>
        </div>
      </div>
    </motion.div>
  )
}

export function ProjectsContent() {
  const [activeFilter, setActiveFilter] = useState<string>("all")
  const filteredProjects = activeFilter === "all" ? projects : projects.filter((p) => p.chain === activeFilter)

  return (
    <div className="mx-auto max-w-7xl px-4 py-24 lg:px-8">
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="mb-12 text-center">
        <h1 className="font-display text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
          Projects <span className="bg-gradient-to-r from-[#00FF88] to-[#00FF88]/60 bg-clip-text text-transparent">&amp; Ecosystem</span>
        </h1>
        <p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-white/50">
          What is live today: the signals suite across Strike and Ascend markets, its verified track record, and the Cardano, Midnight and Ethereum ecosystem positions behind it.
        </p>
      </motion.div>

      <FeaturedSignalsCard />

      <div className="mb-12 grid gap-6 md:grid-cols-2">
        <VenueSignalsCard
          name="Strike Signals"
          color={STRIKE}
          logo="/strike/Strike Logo.jpeg"
          tagline="Every market on Strike Finance perpetuals"
          description="The full signal engine pointed at Strike Finance, the Cardano perpetuals DEX: crypto majors, gold, silver, WTI, US stocks and indices, each with a plain-English recommendation and deep-linked evidence."
          href="/signals/strike"
          venue={{ label: "strikefinance.org", url: "https://app.strikefinance.org" }}
          markets="31 tickers"
        />
        <VenueSignalsCard
          name="Ascend Signals"
          color={ASCEND}
          logo="/avatar/ascend_logo_coin.jpg"
          tagline="The markets behind Ascend event perpetuals"
          description="Bitcoin, Gold, Cardano and WTI — the underlying markets for Ascend's event perpetuals (ZK-settled on Midnight) — with catalyst headline engines and macro event intelligence for each."
          href="/signals/ascend"
          venue={{ label: "ascend.market", url: "https://ascend.market" }}
          markets="BTC · GOLD · ADA · WTI"
        />
      </div>

      <div className="mb-10 flex flex-wrap justify-center gap-2">
        {filterChains.map((chain) => (
          <button
            key={chain}
            onClick={() => setActiveFilter(chain)}
            className={`rounded-full border px-4 py-1.5 text-xs font-medium capitalize transition-all ${
              activeFilter === chain ? "bg-[#00FF88]/15 text-[#00FF88] border-[#00FF88]/30" : "bg-white/[0.03] text-white/40 border-white/[0.06] hover:border-white/[0.12] hover:text-white/60"
            }`}
          >
            {chain === "all" ? "All" : chain}
          </button>
        ))}
      </div>

      <AnimatePresence mode="popLayout">
        <motion.div variants={containerVariants} initial="hidden" animate="show" className="grid gap-6 md:grid-cols-2">
          {filteredProjects.map((project) => (
            <ProjectCard key={project.name} project={project} />
          ))}
        </motion.div>
      </AnimatePresence>

      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.8, duration: 0.5 }} className="mt-16 text-center">
        <p className="text-sm text-white/30">
          Building in public. Follow the journey on{" "}
          <a href="https://x.com/RnGcrYptO" target="_blank" rel="noopener noreferrer" className="text-[#00FF88]/70 transition-colors hover:text-[#00FF88]">@RnGcrYptO</a>
        </p>
      </motion.div>
    </div>
  )
}
